.configure_ssh: &configure_ssh |
  mkdir -p ~/.ssh
  echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
  echo " Host *" > ~/.ssh/config
  echo "    UserKnownHostsFile /dev/null"  >> ~/.ssh/config
  echo "    User deploy"  >> ~/.ssh/config
  echo "    StrictHostKeyChecking no" >> ~/.ssh/config



before_script:
  - *configure_ssh
  

build:
  stage: build
  script: >
    ssh root@usermanager.fbs -i .ssh/id_rsa bash -c "echo -e '\e[0;35m ********** ********** CHANGE WORKING DIR ********** ********** \e[0m';
    cd /home/payment-system-mock/mock-server;
    pwd;
    echo -e '\e[0;35m ********** ********** CLONING REPO ********** ********** \e[0m';
    git pull origin master;
    echo -e '\e[0;35m ********** ********** RESTART MOCK SERVER SERVICE ********** ********** \e[0m';
    systemctl restart payment-system-mock.service"
  only:
    - master
    
